- README.md
- script-base.js
- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/karma.conf.js
- templates/javascript/App.js
- templates/javascript/Component.js
- templates/javascript/main.js
- templates/spec/Component.js
- test/test-creation.js
As requested in https://github.com/newtriks/generator-react-webpack/issues/36. I'm a designer/developer, so please double-check my work! :smile: 
Thanks for the great generator...I use it all the time!
> Update to React 0.12.2

- templates/javascript/Component.js
Currently `yo react-webpack:component Foo/Bar/Blam` will create a component with a style file `styles/Foo/Bar/Blam.scss`, but the component file has a require path of `'../../styles/Blam.scss'`.
> fix the require's style path when creating sub-foldered components

- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/karma.conf.js
6to5 has been renamed to Babel. (See https://github.com/6to5/6to5)
This updates dependencies to reflect the name change.
> 6to5 rename to Babel

- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
The `test` and `exclude` properties had the wrong syntax; they needed to be RegExps not strings.
> Fix jshint preloader

- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
Probably a good idea to exclude js files in `node_modules` from being run through loaders.
> Exclude node_modules from js loaders

- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/karma.conf.js
- templates/javascript/App.js
- templates/javascript/Component.js
- templates/spec/App.js
- templates/spec/Component.js
- templates/spec/main.js
- test/test-creation.js
This feature also fixes #54 
Aliases is built-in feature of webpack's resolve. [Configuration for it](http://webpack.github.io/docs/configuration.html#resolve-alias).
> Provide and use aliases to components dir and styles dir

- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
I noticed the following warnings when using the default generator (not the component) and `grunt serve`. I resolved with the attached changes. Could you add a bit more to the README on how to run the tests for the generator itself? I'd be happy to add some tests if I can figure out how to run them :)
````
WARNING in ./src/scripts/components/main.js
jshint results in errors
Unclosed regular expression. @ line 10 char 52
<Route name="/" handler={MyApp}/>
Unrecoverable syntax error. (58% scanned). @ line 10 char 52
undefined
WARNING in ./src/scripts/components/MyApp.js
jshint results in errors
Unclosed regular expression. @ line 17 char 31
Unrecoverable syntax error. (68% scanned). @ line 17 char 31
undefined
````
> make jsx hint default to resolve warnings when compiling

- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/karma.conf.js
babel-loader also supports jsx, so let's use one common loader?
> Use babel-loader instead of jsx-loader

- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
Hi there,
First of all, thanks for this great generator, it really kickstarted my experience with react & friends.
Unfortunately the sass loader needs to be reminded, that in `.sass` sass content is expected, so I added a small annotation. Additionally, as sass seems to have problems with the installation on OSX in this version number I updated it. So this PR should additionally fix #79 and #67 
Have a nice day!
> Sass loader now expects sass files to contain sass instead of scss

- README.md
- script-base.js
- templates/common/Gruntfile.js
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/gitignore
- templates/common/karma.conf.js
- templates/javascript/App.js
- test/test-creation.js
Fixes #88 by removing the "scripts" path, conforming to where the files were actually being generated. 
I personally think it's clearer to have components, actions and stores right beneath `src`, rather than one folder down (`src/scripts`).
> Fix broken script and style paths

- package.json
This project assumes that the user has `grunt` installed, but that isn't always the case - this will make it easier for less experienced front-end developers to get up and running without having to separately install `grunt` and `grunt-cli`.
If you don't think this is a necessary addition to `package.json` we could always add a comment to the `README` instead?
> Add grunt & grunt-cli to devDependencies

- README.md
- a/index.js
- action/index.js
- c/index.js
- component/index.js
- package.json
- s/index.js
- script-base.js
- store/index.js
- templates/common/index.html
- templates/javascript/Component.js
in this pull request:
1. alias for generators : `a`,`c`,`s` (action,store,component).
2. `rich` flag when generating a component.
3. protection against empty name in action/store generator (prev resulted :`UndefinedStore`)  
4. updated readme and description in package.json (that's what displayed in yeoman's site)
> alias for generators, rich option

- action/index.js
- app/index.js
- main/index.js
- store/index.js
- templates/common/_package.json
- templates/javascript/AltAction.js
- templates/javascript/AltStore.js
- templates/javascript/alt.js
Added architecture option for [Alt Flux library](https://github.com/goatslacker/alt) including sub-generators for actions and stores, supporting `--es6` flag too.
> Added architecture option for Alt (http://alt.js.org)

- templates/common/_package.json
- templates/common/_webpack.config.js
- templates/common/_webpack.dist.config.js
- templates/common/root/.eslintrc
- test/test-creation.js
Added eslint as new linter to webpack configuration. Please note that the webpack.NoErrorsPlugin does not work with eslint-loader correctly. Whenever eslint-loader throws an error or warning while using webpack.NoErrors, the build is suspended.
Therefore it was removed in the regular webpack.config, but included in the live version (because there it could be of value).
Please tell me what you think about it.
> *ADD* Base: Added esLint as new linter

- templates/javascript/Component.js
This fixes the linter error: `error  Trailing spaces not allowed  no-trailing-spaces`
> Remove trailing whitespace after Reflux

- generators/app/index.js
npm@3 now flattens node_modules directory
This should be happy no matter where the module ends up
> update baseRootPath to be happier with npm@3

- generators/app/index.js
- test/generators/app/indexTest.js
npm converts `.gitignore` to `.npmignore` in `react-webpack-template` package
https://github.com/npm/npm/issues/3763
> Add .gitignore file to generated application

- jsconfig.json
Adds support for Visual Studio Code IDE. This requires a *jsconfig.json* at the root. 
https://code.visualstudio.com/docs/languages/javascript
> Added support for Visual Studio Code

- test/generators/component/indexTest.js
- test/utils/yeomanTest.js
- utils/yeoman.js
Wrapped Node's `path.normalize()` around paths that have `componentPartPath` as a part segment. For non-namespaced components this segment can be empty which lead to two consecutive slashes in various places.
Updated test suite to assert against the updated import statements in various files.
PR for #253
> Prevent two consecutive slashes in test imports #253

- generators/app/index.js
> Updated prompting to new yeoman-generator api

- generators/app/postcss.js
- package.json
- test/generators/app/indexTest.js
Primarly needed to update the way, the postcss related stuff is attached since it is attached to the webpack config, which has changed.
> V4 -- Update for template v2.0.1-5

- generators/setup-env/constants.js
- generators/setup-env/index.js
- generators/setup-env/templates/4/Env.js
- generators/setup-env/templates/4/runtimeConfig.js
- generators/setup-env/utils.js
- package.json
- test/generators/setup-env/assets/moduleIndex.js
- test/generators/setup-env/setupEnvTest.js
This subgen creates a new Webpack config environment by
- creating conf/webpack/<EnvName>.js
- creating src/config/<env_name>.js
- requiring and exporting the new env in conf/webpack/index.js
The commit introduces a basic config template that is supposed to be populated by the generator's users. Various more fine grained subgen options can be added at a later time (e.g. prompting the user if new run scripts should be added to package.json).
The subgen's basic functionality is backed up by unit tests that check
- if files are created
- if conf/webpack/index.js contains correct import/export
> Added sub-generator setup-env #278

- generators/component/index.js
- test/utils/yeomanTest.js
- utils/yeoman.js
This feature allows users to put a `cssClsPrefix` property into their
.yo-rc.json. If configured, the component generator will add this string
as a prefix to className attributes.
Example:
// .yo-rc.json
{
"generator-react-webpack": {
"appName": "v4-latest-install",
"style": "css",
"cssmodules": false,
"cssClsPrefix": "myapp",
"postcss": false,
"generatedWithVersion": 4
}
}
Components generated will now prepend the `myapp` prefix on their class
names, e.g.
$ yo react-webpack:component hello
<div className="myapp-hello-component" />
> Added support for configuring a className prefix
